server:
  port: 9002
#对Feign的支持
feign:
  sentinel:
    enabled: true
ribbon:
  eager-load:
    enabled: off
spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  mvc:
    servlet:
      path: /
    view:
      suffix: .html
