-- auto Generated on 2021-04-28
-- DROP TABLE IF EXISTS order_base;
CREATE TABLE `test_order`(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	cell_phone VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'cellPhone',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	create_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
	INDEX(id),
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'test_order';
