server:
  port: 9001
spring:
  # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.200.222.212:33060/test01?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: dc.342624
          druid:
            validationQuery: SELECT 1
        slave_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.200.222.212:33060/test02?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: dc.342624
          druid:
            validationQuery: SELECT 1
      #        oracle:
      #          url: jdbc:wrap-jdbc:filters=encoding:jdbc:oracle:thin:@com.wxsk.xf.db:1521:ORCL
      #          username: develop_test_4
      #          password: 6sAKodk1UKqYfH7hLriR
      #          driver-class-name: oracle.jdbc.driver.OracleDriver
      initial-size: 10 # 以下是连接池配置
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
#    数据源配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://101.200.222.212:9996/test01?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: dc.342624
#    druid:
#      validationQuery: SELECT 1



# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: info
mybatis-plus:
  #  日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    #开启驼峰命名的配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapperxml/*.xml